image: Visual Studio 2017

environment:
  EnableNuGetPackageRestore: true
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
- packages -> **\ESBreakerCLI\packages.config
- ESBreakerCLI\lib\

configuration:
- Release
- Debug

build:
  parallel: true
  verbosity: minimal

before_build:
- cmd: nuget restore -NonInteractive -Verbosity quiet

after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%\gitshort.txt
- cmd: set /P GITSHORT=<%TMP%\gitshort.txt
- set BUILD_ARCHIVE=%APPVEYOR_REPO_BRANCH%-%GITSHORT%-%CONFIGURATION%.7z
- cmd: cd "ESBreakerCLI\bin\"
- cmd: cd "%CONFIGURATION%"
- cmd: 7z a %BUILD_ARCHIVE% *.* -xr!.gitignore -x!ContentsSerializer.dll -x!Assembly-CSharp-firstpass.dll -x!UnityEngine.dll -x!protobuf-net.dll -x!ProtoBuffSerializer.dll -x!*.xml
- appveyor PushArtifact %BUILD_ARCHIVE%
- cmd: cd ..\..\..
- cmd: del /F /Q ESBreakerCLI\lib\*.dll ESBreakerCLI\lib\*.zip
